//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.webacesso.entities;

import br.jus.trt23.nucleo.entities.EntidadeGenerica;
import br.jus.trt23.webacesso.constants.Constantes;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
@Table(schema = Constantes.SCHEMA)
public class PapelRecurso extends EntidadeGenerica<Long>{
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id")
    @SequenceGenerator(
            schema = Constantes.SCHEMA, sequenceName = "papelrecurso_seq", name = "id"
    )
    protected Long id;
    @ManyToOne(targetEntity = Recurso.class)
    private Recurso recurso;

    @ManyToOne(targetEntity = RecursoPermissao.class)
    private RecursoPermissao permissao;

    @ManyToOne(targetEntity = Papel.class)
    private Papel papel;

    public PapelRecurso() {

    }
    @Override
    public String getNomeNatural() {
        return "Recursos por papel";
    }
}
