//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.webacesso.entities;

import br.jus.trt23.nucleo.entities.EntidadeGenerica;
import br.jus.trt23.webacesso.constants.Constantes;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
@Table(schema = Constantes.SCHEMA)
public class RunAs extends EntidadeGenerica<Long>{
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id")
    @SequenceGenerator(
            schema = Constantes.SCHEMA, sequenceName = "runas_seq", name = "id"
    )
    
    protected Long id;
    @ManyToOne(targetEntity = Sistema.class)
    private Sistema sistema;

    @ManyToOne(targetEntity = Usuario.class)
    private Usuario usuario;

    public RunAs() {

    }
    
    @Override
    public String getNomeNatural() {
        return "Run as";
    }
}
