//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.webacesso.entities;

import br.jus.trt23.nucleo.entities.EntidadeGenerica;
import br.jus.trt23.webacesso.constants.Constantes;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
@Table(schema = Constantes.SCHEMA)
public class Sistema extends EntidadeGenerica<Long>{
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id")
    @SequenceGenerator(
            schema = Constantes.SCHEMA, sequenceName = "sistema_seq", name = "id"
    )
    
    protected Long id;
    @OneToMany(targetEntity = RunAs.class, mappedBy = "sistema", cascade = {CascadeType.MERGE,CascadeType.PERSIST, CascadeType.REFRESH})
    private Set<RunAs> runAses;

    @Column(unique = true, nullable = false, length = 6)
    @Basic
    private String sigla;

    @OneToMany(targetEntity = Flow.class, mappedBy = "sistema", cascade = {CascadeType.MERGE,CascadeType.PERSIST, CascadeType.REFRESH})
    private Set<Flow> flows;

    @Column(unique = true, nullable = false)
    @Basic
    private String nome;

    @OneToMany(targetEntity = Delegacao.class, mappedBy = "sistema", cascade = {CascadeType.MERGE,CascadeType.PERSIST, CascadeType.REFRESH})
    private Set<Delegacao> delegacoes;

    @OneToMany(targetEntity = Papel.class, mappedBy = "sistema", cascade = {CascadeType.MERGE,CascadeType.PERSIST, CascadeType.REFRESH})
    private Set<Papel> papeis;

    @OneToMany(targetEntity = Recurso.class, mappedBy = "sistema", cascade = {CascadeType.MERGE,CascadeType.PERSIST, CascadeType.REFRESH})
    private Set<Recurso> recursos;

    @Column(unique = true, nullable = false)
    @Basic
    private String url;

    @Basic
    private String descricao;

    public Sistema() {
        recursos = new HashSet();
        papeis = new HashSet();
        delegacoes = new HashSet();
        flows = new HashSet();
        runAses = new HashSet();
    }
    
    public void addRecursos(Recurso recurso){
        recursos.add(recurso);
        recurso.setSistema(this);
    }
    
    public void addPapeis(Papel papel){
        papeis.add(papel);
        papel.setSistema(this);
    }

    public void addDelegacoes(Delegacao delegacao){
        delegacoes.add(delegacao);
        delegacao.setSistema(this);
    }

    public void addFlows(Flow flow){
        flows.add(flow);
        flow.setSistema(this);
    }
    
    public void addRunAses(RunAs runAs){
        runAses.add(runAs);
        runAs.setSistema(this);
    }
    
    
    @Override
    public String getNomeNatural() {
        return "Sistema";
    }
}
