//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.webacesso.entities;

import br.jus.trt23.nucleo.entities.EntidadeGenerica;
import br.jus.trt23.webacesso.constants.Constantes;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
@Table(schema = Constantes.SCHEMA)
public class UsuarioTipo extends EntidadeGenerica<Long>{
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "id")
    @SequenceGenerator(
            schema = Constantes.SCHEMA, sequenceName = "usuariotipo_seq", name = "id"
    )
    protected Long id;
    
    @Basic
    private String nome;

    @OneToMany(targetEntity = Usuario.class, mappedBy = "tipo")
    private Set<Usuario> usuarios;

    public UsuarioTipo() {
        usuarios = new HashSet();
    }

    @Override
    public String getNomeNatural() {
        return "Tipo de usuário";
    }
}
