//
// This file was generated by the JPA Modeler
//
package br.jus.trt23.webacesso.entities;

import br.jus.trt23.webacesso.constants.Constantes;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)
@Table(schema = Constantes.SCHEMA, name = "USUARIOEXTERNO")
public class UsuarioExterno extends Usuario{
   
    public UsuarioExterno() {

    }
}
